rails/nano_online/trunk/config/routes.rb
NanoOnline::Application.routes.draw do
  root :to => 'static#home'
  match 'customer_login/login'    => 'customer_login#login'
  match 'customer_login'          => 'customer_login#index'
  match 'customer_login/cadastro' => 'customer_login#cadastro'
  match 'customer_login/do_login' => 'customer_login#do_login'
  match 'customer_login/create'   => 'customer_login#create'
  match 'customers/remember_password' => 'customers#remember_password'
  match 'validate/:hash'          => 'customer_login#validate'
  match 'users/change_password'   => 'users#change_password'
  match 'users/recover_password'  => 'users#recover_password'
  match 'users/user_info'         => 'users#user_info'
  match 'login/login'             => 'login#login'
  match 'admin'                   => 'login#login'
  match 'login/logout'            => 'login#logout'
  match 'login/index'             => 'login#index'

  match '/apps', :controller => 'apps', :action => 'index', :constraints => {:method => 'OPTIONS'}

  resources :app_categories, :ad_channel_statuses, :ad_piece_versions, :families,
    :midp_versions, :cldc_versions,
    :app_versions, :bands, :data_services, :device_bugs, :optional_apis, :operators, :integrators,
    :download_codes, :user_roles, :partners, :users, :session_storage,
    :midlet_reports, :news_feed_categories, :ranking_types, :unit_formats, :ranking_systems,
    :ad_campaigns, :ad_pieces, :advertisers, :resources, :resource_files,
    :resource_types, :ad_channels, :resource_file_types

  resources :sessions, :only => [:new, :create, :destroy]
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/login' => 'sessions#new', :as => 'login'
  match '/auth/:provider/callback' => 'sessions#create'

  resources :registrations

  resources :ad_channel_versions do
    collection do
      get :delete_composition
    end
  end

  resource :app_customer_data do
    collection do
      post :save_data
      post :load_data
    end
  end

  resource :app_versions do
    member do
      get :create_updated_app_version
    end
  end

  resources :ranking_entries, :except => [:show] do
    collection do
      get   :user_range_high_score
      get   :high_scores
      post  :submit
      get   :update_high_scores
    end
  end

  resources :static do
    member do
      post :web_contact
    end
  end

  resources :apple_downloads do
    collection do
      post :csv
    end
  end

  resources :customers do
    collection do
      post :login
      post :import
      post :add
      post :refresh
    end
  end

  resources :submissions do
    member do
      get :generate
    end
  end

  resources :news_feeds do
    member do
      post :refresh
    end
  end

  # resources :downloads do
  #   collection do
  #     get :vendor_select
  #   end
  # end

  # TODO mudar downloads para um resource
  match 'downloads/app' => 'downloads#download_app'
  match 'downloads/select_device' => 'downloads#select_device'
  match 'downloads/select_app' => 'downloads#select_app'
  match 'downloads/download_jar_file' => 'downloads#download_jar_file'
  match 'downloads/download_jad' => 'downloads#download_jad'
  match 'downloads/' => 'downloads#select_vendor'
  match 'downloads/download' => 'downloads#download'
  match 'downloads/index' => 'downloads#index'
  match 'downloads/download_axe_mobile' => 'downloads#download_axe_mobile'
  match 'downloads/download_seda_puzzle' => 'downloads#download_seda_puzzle'
  match 'downloads/server_error' => 'downloads#server_error'

  match 'apple_downloads' => 'apple_downloads#index'
  match 'apple_downloads/upload_file' => 'apple_downloads#upload_file'
  match 'undetected_user_agents' => 'undetected_user_agents#index'
  match 'submissions/generate' => 'submissions#generate'

  match 'boadica/categories' => 'boadica#categories'
  match 'boadica/store' => 'boadica#store'
  match 'boadica/offers' => 'boadica#offers'
  match 'download/:id' => 'downloads#download_file_by_id'
  match 'test/' => 'test#detect'
  # match 'high_scores/' => 'ranking_entries#high_scores'
  # match 'high_scores/.:format' => 'ranking_entries#high_scores'
  # match 'user_range_high_score/.:format' => 'ranking_entries#user_range_high_score'
  match 'notify/i/:id' => 'midlet_reports#install', :id => /.*(\d{1,2}\.\d{1,2}((\.\d{0,2}){0,1}))?/
  match 'notify/d/:id' => 'midlet_reports#delete', :id => /.*(\d{1,2}\.\d{1,2}((\.\d{0,2}){0,1}))?/
  match 'notify/install/:id' => 'midlet_reports#install', :id => /.*(\d{1,2}\.\d{1,2}((\.\d{0,2}){0,1}))?/
  match 'notify/delete/:id' => 'midlet_reports#delete', :id => /.*(\d{1,2}\.\d{1,2}((\.\d{0,2}){0,1}))?/

  resources :vendors do
    collection do
      get :list
    end
  end

  resources :devices do
    collection do
      get :list
    end
  end

  resources :apps do
    collection do
      get :list
    end
  end

  namespace :imuz_db do
    resource :game_sessions do
      member do
        post  :frame
        get   :frame if Rails.env.development?
        get   :home
        get   :news
        get   :start
        get   :new_question_iphone
        post  :respond
        get   :next_question
        get   :skip_question
        get   :missed_question
        get   :correct
        get   :wrong
        get   :game_over
        get   :ranking
        get   :choose_nickname
        post  :set_nickname
        get   :friend_list
        post  :invite_friends
        get   :facebook_share
        get   :help
        post  :audio_state
        get   :profile
        get   :prepare_share
        get   :facebook_error
      end
    end
    resource :pages
  end

  match 'portfolio' => 'static#portfolio_2010', :as => :portfolio
  match 'vila_virtual' => 'static#vila_virtual', :as => :vila_virtual

  match "/customer_login/update/:id" => 'customer_login#update', :as => :update_customer_login, :method => :put
  match "/imuz_db/mobile/forget_password" => 'customer_login#forget_password', :as => :forget_password_customer_login
  match "/imuz_db/mobile/resend_password" => 'customer_login#resend_password', :as => :resend_password_customer_login, :method => :post
  match "/imuz_db/mobile/login" => 'customer_login#login'
  match "/imuz_db/mobile/sign_up" => 'customer_login#sign_up'
  match "/imuz_db/mobile/home" => 'imuz_db/game_sessions#home'
  match "/imuz_db/mobile/first_use" => 'customer_login#first_use'
  match "/imuz_db/mobile/fb_session" => 'imuz_db/game_sessions#fb_session'
  match "/imuz_db/mobile/fb_login" => 'imuz_db/game_sessions#fb_login'
  match "/imuz_db/mobile/installation" => 'customer_login#installation'
  match "/imuz_db/mobile" => 'customer_login#installation'
  match "/imuz_db/mobile/ajax_login" => 'customer_login#ajax_login'
  match "/imuz_db/mobile/new_question_ajax" => 'imuz_db/game_sessions#new_question_iphone'
  match "/customer_login/edit" => 'customer_login#edit'
  match "imuz_db/do_login" => 'customer_login#do_login'

  # map.resources :customer_login, :collection => {:do_login => :post, :sign_up => :get, :first_use => :get}

  match '/about' => 'static#about'
  match '/down' => 'static#download'
  match '/news' => 'static#news'
  match '/partner' => 'static#partners'
  match '/contact' => 'static#web_contact'
  match '/portfolio' => 'static#portfolio_2010'
  match '/vila_virtual' => 'static#vila_virtual'
end

rails/nano_online/trunk/app/models/app.rb
# == Schema Information
#
# Table name: apps
#
#  id                      :integer(4)      not null, primary key
#  name                    :text(255)       default(""), not null
#  name_short              :text(255)       default(""), not null
#  description_short       :text
#  description_medium      :text
#  description_long        :text
#  created_at              :datetime
#  updated_at              :datetime
#  apple_title             :string(255)
#  apple_vendor_identifier :string(255)
#  apple_identifier        :string(255)
#

class App < ActiveRecord::Base
  has_and_belongs_to_many :app_categories
  has_and_belongs_to_many :partners
  has_and_belongs_to_many :ad_campaigns
  has_and_belongs_to_many :ads
  has_many :app_versions
  has_many :ranking_entries, :through => :app_versions # TODO necessário?
  has_many :apple_downloads
  has_one :facebook_data
  has_many :facebook_feeds

  validates_presence_of :name, :name_short
  validates_uniqueness_of :name, :case_sensitive => false
  validates_uniqueness_of :name_short, :case_sensitive => false
  validates_length_of :name, :in => 3..50
  validates_length_of :name_short, :is => 4
  validates_length_of :description_short, :maximum => 150, :allow_nil => true
  validates_length_of :description_medium, :maximum => 300, :allow_nil => true
  validates_length_of :description_long, :maximum => 900, :allow_nil => true

  scope :by_device, lambda { |device_id| where(:id => [Device.find(device_id).family.app_versions.map {|av| av.app_id}])}
  scope :by_vendor, lambda { |vendor_id| includes(:app_versions => [:families => [:devices => :vendor]]).where('ven@dors.id' => vendor_id) }
  scope :name_and_id, select([:name, :id])
  scope :with_available_versions, includes(:app_versions).where("app_versions.status = 'Available'")

  def families
    Family.all(:include => { :app_versions => :app }, :conditions => ["apps.id = ?", self.id])
  end

  def devices
    Device.all(:include => { :family => { :app_versions => :app } }, :conditions => ["apps.id = ?", self.id], :order => 'devices.model')
  end

  def vendors
    Vendor.all(:include => { :devices => { :family => { :app_versions => :app } } }, :conditions => ["apps.id = ?", self.id], :order => 'vendors.name')
  end

  def name_clean
    name.gsub( ' ', '_' )
  end

  def find_version_with_support_to(device)
    self.app_versions.each do |version|
      if version.devices.include?(device) && version.state.name == "Available"
        return version
      end
    end
  end
  def customers
    Customer.where("ranking_entries.app_version_id in (#{self.app_version_ids.join(',')})").includes(:ranking_entries).order("customers.created_at")
  end
end

rails/nano_online/trunk/app/views/apps/edit.html.erb
<h1> <%= h "Editing application #{ @app.name }" %> </h1>

<%= form_for(@app) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :name_short %><br />
    <%= f.text_field :name_short %>
  </p>
  <p>
    <%= f.label :description_short %><br />
    <%= f.text_area :description_short, :size => '75x2' %>
  </p>
  <p>
    <%= f.label :description_medium %><br />
    <%= f.text_area :description_medium, :size => '75x4' %>
  </p>
  <p>
    <%= f.label :description_long %><br />
    <%= f.text_area :description_long, :size => '75x12' %>
  </p>
  <p>
    <%= f.label :apple_title %><br />
    <%= f.text_field :apple_title, :size => '75x12' %>
  </p>
  <p>
	Categories:
	<%
	  app_categories = AppCategory.find( :all )
	  if ( app_categories.empty? )
	%>
	<br/>No categories found in database.<br/>
	<%
	  else
	   for app_category in app_categories
	%>
	  <div>
		<%= check_box_tag "app[app_category_ids][]", app_category.id, @app.app_categories.include?( app_category ) %>
		<%= h app_category.name %>
	  </div>
	<%
		end
	  end 
	%>
  </p>

  <p>
	Partners:
	<%
	  partners = Partner.find( :all, :order => 'name' )
	  if ( partners.empty? )
	%>
	<br/>No partners found in database.<br/>
	<%
	  else
	   for partner in partners
	%>
	  <div>
		<%= check_box_tag "app[partner_ids][]", partner.id, @app.partners.include?( partner ) %>
		<%= h partner.name %>
	  </div>
	<%
		end
	  end
	%>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

rails/nano_online/trunk/app/views/apps/index.html.erb
<div>
  <table id="table" border="1" >
		<thead>
			<tr>
	      <th>Id</td>
	      <th>Name</td>
	      <th>Short name</td>
	      <th>Description short</td>
	      <th>Description medium</td>
	      <th>Description long</td>
	      <th>Categories</td>
	      <th>Partners</td>
				<th colspan="3"></th>
	    </tr>
		</thead>

		<tbody>
			<% @apps.each do |app| %>
	      <tr valign="top" >

	        <td><%=h app.id %></td>
					<td><%=h app.name %></td>
					<td><%=h app.name_short %></td>
					<td><%=h app.description_short %></td>
					<td><%=h app.description_medium %></td>
					<td><%=h app.description_long %></td>
					<%= render( :partial => 'app_categories', :object => app.app_categories ) %>
					<td><%=h app.partners.empty? ? 'none' : app.partners.collect { |p| p.name }.join( ', ' ) %></td>

	        <% if current_user.is_admin? %>
	          <td class="list-actions" ><%= link_to 'Show', app %></td>
	          <td class="list-actions" ><%= link_to 'Edit', edit_app_path(app) %></td>
	          <td class="list-actions" ><%= link_to 'Destroy', app, :confirm => "Remove app " + app.name + '?', :method => :delete %></td>
	        <% end %>
	      </tr>
	    <% end %>
		</tbody>
  </table>
	<br/>
</div>

<%= paginate @apps %>

<br />
<%= if ( current_user.is_admin? ) then link_to 'Add application', new_app_path end %>

rails/nano_online/trunk/app/views/apps/new.html.erb
<h1>New app</h1>

<%= form_for(@app) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :name_short %><br />
    <%= f.text_field :name_short %>
  </p>
  <p>
    <%= f.label :description_short %><br />
    <%= f.text_area :description_short, :size => '75x2' %>
  </p>
  <p>
    <%= f.label :description_medium %><br />
    <%= f.text_area :description_medium, :size => '75x4' %>
  </p>
  <p>
    <%= f.label :description_long %><br />
    <%= f.text_area :description_long, :size => '75x12' %>
  </p>
  <p>
    <%= f.label :apple_title %><br />
    <%= f.text_field :apple_title, :size => '75x12' %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', apps_path %>

rails/nano_online/trunk/app/views/apps/show.html.erb
<p>
  <b>Name:</b>
  <%= @app.name %>
</p>
<p>
  <b>Short name:</b>
  <%= @app.name_short %>
</p>
<p>
  <b>Short description:</b>
  <%= @app.description_short %>
</p>
<p>
  <b>Medium description:</b>
  <%= @app.description_medium %>
</p>
<p>
  <b>Long description:</b>
  <%= @app.description_long %>
</p>
<p>
  <b>Apple Title:</b>
  <%= @app.apple_title %>
</p>
<p>
  <b>Categories:</b><br/>
  <%= render( :partial => 'app_categories', :object => @app.app_categories ) %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>